
#Settings
[settings]
	#Whether Blocks and Entities slow the creative player down when carried
	slownessInCreative = true
	#Use Whitelist instead of Blacklist for Stacking
	useWhitelistStacking = false
	#Allow all blocks to be picked up, not just Tile Entites
	pickupAllBlocks = false
	#Slowness multiplier for entities
	#Range: 0.0 ~ 1.7976931348623157E308
	entitySlownessMultiplier = 1.0
	#Use Whitelist instead of Blacklist for Entities
	useWhitelistEntities = false
	#Maximum distance from where Blocks and Entities can be picked up
	#Range: 0.0 ~ 1.7976931348623157E308
	maxDistance = 2.5
	#Whether the player can hit blocks and entities while carrying or not
	hitWhileCarrying = false
	#More complex Tile Entities slow down the player more
	heavyTiles = true
	#Max width of entities that can be picked up in survival mode
	#Range: 0.0 ~ 10.0
	maxEntityWidth = 1.5
	#Whether the player drops the carried object when hit or not
	dropCarriedWhenHit = false
	#Use Whitelist instead of Blacklist for Blocks
	useWhitelistBlocks = false
	#Larger Entities slow down the player more
	heavyEntities = true
	#Allow babies to be carried even when adult mob is blacklisted (or not whitelisted)
	allowBabies = false
	#Use custom Pickup Scripts. Having this set to false, will not allow you to run scripts, but will increase your performance
	useScripts = false
	#Max height of entities that can be picked up in survival mode
	#Range: 0.0 ~ 10.0
	maxEntityHeight = 1.5
	#Maximum stack limit for entities
	#Range: > 1
	maxEntityStackLimit = 10
	#Whether entities' size matters when stacking or not
	stackableEntities = true
	#Whether hostile mobs should be able to picked up in survival mode
	pickupHostileMobs = false
	#Slowness multiplier for blocks
	#Range: 0.0 ~ 1.7976931348623157E308
	blockSlownessMultiplier = 1.0

[blacklist]
	#Entities that cannot have other entities stacked on top of them
	forbiddenStacking = ["minecraft:horse"]
	#Entities that cannot be picked up
	forbiddenEntities = ["minecraft:end_crystal", "minecraft:ender_dragon", "minecraft:ghast", "minecraft:shulker", "minecraft:leash_knot", "minecraft:armor_stand", "minecraft:item_frame", "minecraft:painting", "minecraft:shulker_bullet", "animania:hamster", "animania:ferret*", "animania:hedgehog*", "animania:cart", "animania:wagon", "mynko:*", "pixelmon:*", "mocreatures:*", "quark:totem", "computercraft:*"]
	#Blocks that cannot be picked up
	forbiddenTiles = ["minecraft:end_portal", "minecraft:end_gateway", "minecraft:tall_grass", "minecraft:large_fern", "minecraft:peony", "minecraft:rose_bush", "minecraft:lilac", "minecraft:sunflower", "minecraft:*_bed", "minecraft:oak_door", "minecraft:iron_door", "minecraft:spruce_door", "minecraft:birch_door", "minecraft:jungle_door", "minecraft:acacia_door", "minecraft:dark_oak_door", "minecraft:waterlily", "minecraft:cake", "minecraft:nether_portal", "minecraft:tall_seagrass", "animania:block_trough", "animania:block_invisiblock", "colossalchests:*", "ic2:*", "bigreactors:*", "forestry:*", "tconstruct:*", "rustic:*", "botania:*", "astralsorcery:*", "quark:colored_bed_*", "immersiveengineering:*", "embers:block_furnace", "embers:ember_bore", "embers:ember_activator", "embers:mixer", "embers:heat_coil", "embers:large_tank", "embers:crystal_cell", "embers:alchemy_pedestal", "embers:boiler", "embers:combustor", "embers:catalzyer", "embers:field_chart", "embers:inferno_forge", "storagedrawers:framingtable", "skyresources:*", "lootbags:*", "exsartagine:*", "aquamunda:tank", "opencomputers:*", "malisisdoors:*", "industrialforegoing:*", "minecolonies:*", "thaumcraft:pillar*", "thaumcraft:infernal_furnace", "thaumcraft:placeholder*", "thaumcraft:infusion_matrix", "thaumcraft:golem_builder", "thaumcraft:thaumatorium*", "magneticraft:oil_heater", "magneticraft:solar_panel", "magneticraft:steam_engine", "magneticraft:shelving_unit", "magneticraft:grinder", "magneticraft:sieve", "magneticraft:solar_tower", "magneticraft:solar_mirror", "magneticraft:container", "magneticraft:pumpjack", "magneticraft:solar_panel", "magneticraft:refinery", "magneticraft:oil_heater", "magneticraft:hydraulic_press", "magneticraft:multiblock_gap", "refinedstorage:*", "mcmultipart:*", "enderstorage:*", "betterstorage:*", "practicallogistics2:*", "wearablebackpacks:*", "rftools:screen", "rftools:creative_screen", "create:*", "waystones:*", "mekanism:*", "mekanismgenerators:*", "computercraft:*"]

[whitelist]
	#Entities that CAN have other entities stacked on top of them (useWhitelistStacking must be true)
	allowedStacking = []
	#Blocks that CAN be picked up (useWhitelistBlocks must be true)
	allowedBlocks = []
	#Entities that CAN be picked up (useWhitelistEntities must be true)
	allowedEntities = []

[custom_pickup_conditions]
	#Custom Pickup Conditions for Blocks
	customPickupConditionsBlocks = []
	#Custom Pickup Conditions for Entities
	customPickupConditionsEntities = []
