
#General Configuration
[general]
	#The list of slabs (or tags) to ignore when creating double slabs
	#Example: minecraft:purpur_slab
	slabBlacklist = []
	#The list of slabs (or tags) to ignore when creating vertical slabs
	#Example: minecraft:purpur_slab
	#Example: #minecraft:slabs
	verticalSlabBlacklist = []
	#Whether to use the custom double slab when combining slabs of the same type
	replaceSameSlab = false
	#Whether to disable the placement of vertical slabs from regular horizontal slabs
	disableVerticalSlabPlacement = true
	#The list of slabs (or tags) to ignore when trying to convert between a regular slab and a vertical slab item
	#Use the wildcard value * to disable this feature for all slabs
	verticalSlabCraftingBlacklist = []

