#Minimum time in ticks for leaf decay. Must be lower than MaximumDecayTime!
#Range: > 0
MinimumDecayTime = 21
#Maximum time in ticks for leaf decay. Must be higher than MinimumDecayTime!
#Range: > 0
MaximumDecayTime = 46
