
[general]
	#Should clientside fog be rendered?
	"Atum Fog" = true
	#Can a non-creative user create a portal using the scarab?
	"Atum Portal" = true

["atum start"]
	#Structure that will generate next to the player when starting in Atum (Requires 'Start in Atum' to be enabled). Leave empty for no structure.
	"Atum starting structure" = "atum:tent_small"
	#Should a portal back to the Overworld generate, when starting in Atum?
	"Create Atum Portal" = false
	#New players should start in Atum?
	"Start in Atum" = false

[sandstorm]
	#Sand particle transparency while wearing Sandstorm reducing helmets
	#Range: 0 ~ 100
	"Sandstorm Helmet Transparency" = 40
	#Multiplier to fog during sandstorms
	#Range: 0 ~ 100
	"Sandstorm Fog" = 2
	#Seconds it takes to transition from clear to sandstorm
	#Range: 0 ~ 100
	"Sandstorm Transition Time" = 25
	#Chance for sandstorms to generate sand layers. The higher the value, the more rare it is. Set to 0 to disable.
	#Range: 0 ~ 10000
	"Sandstorm Sand Layer" = 60
	#How light the sand particles are
	#Range: 0 ~ 100
	"Sandstorm Brightness" = 75
	#Enable/disables all functionality of sandstorms
	"Sandstorm Enabled" = false
	#Base transparency for sand particles
	#Range: 0 ~ 100
	"Sandstorm Base Transparency" = 10

["world gen"]
	#Should Ruins generate in Atum?
	"Enable Ruins" = true
	#Should Pyramids generate in Atum?
	"Enable Pyramids" = true
	#Specify the amount of ruin variants structures/ruins. Allows for additional ruin structures with a resourcepack
	#Range: 1 ~ 999
	"Ruins Amount" = 19
	#Should Mineshafts generate in Atum?
	"Enable Mineshafts" = true
	#Sets above what Y-level water will vaporize at (Except Oasis). Set to 0 to disable
	#Range: 0 ~ 255
	"Water Level" = 50
	#Should Sand Layers generate along all edges?
	"Enable Sand Layer along edges" = true

[biome]
	#By default 1 in 30 Sand Plains or Sand Dunes biomes can contain either an Oasis or Dead Oasis. Set to 0 to disable both oases biomes.
	#Range: 0 ~ 10000
	"Oases chance" = 30
	#Sets the percentage chance for oases to generate as an Oasis. The remaining oases will generate as an Dead Oasis. Set to 0 to only get Dead Oasis or to 100 to only get Oasis
	#Range: 0 ~ 10000
	"Oasis percentage" = 50

	[biome.sand_dunes]
		#Range: -1 ~ 1000
		weight = 15

	[biome.deadwood_forest]
		#Range: -1 ~ 1000
		weight = 10

	[biome.sand_hills]
		#Range: -1 ~ 1000
		weight = 10

	[biome.limestone_crags]
		#Range: -1 ~ 1000
		weight = 3

	[biome.limestone_mountains]
		#Range: -1 ~ 1000
		weight = 5

	[biome.sand_plains]
		#Range: -1 ~ 1000
		weight = 30

[mobs]
	#How frequent Bandit patrols are. The higher the number, the less patrols will spawn
	#Range: -1 ~ 10000
	banditPatrolFrequency = 330
	#How long time is required for an Assassin to spawn. The higher the number, the less frequent Assassin will spawn
	#Range: 1 ~ 10000
	markedForDeathFrequency = 1000

	[mobs.bonestorm]
		#Range: -1 ~ 63
		min = 1
		#Range: 1 ~ 64
		max = 2
		#Range: -1 ~ 1000
		weight = 5

	[mobs.wraith]
		#Range: -1 ~ 63
		min = 1
		#Range: 1 ~ 64
		max = 2
		#Range: -1 ~ 1000
		weight = 10

	[mobs.desert_wolf]
		#Range: -1 ~ 63
		min = 2
		#Range: 1 ~ 64
		max = 4
		#Range: -1 ~ 1000
		weight = 5

	[mobs.bat]
		#Range: -1 ~ 63
		min = 8
		#Range: 1 ~ 64
		max = 8
		#Range: -1 ~ 1000
		weight = 5

	[mobs.camel]
		#Range: -1 ~ 63
		min = 2
		#Range: 1 ~ 64
		max = 6
		#Range: -1 ~ 1000
		weight = 6

	[mobs.mummy]
		#Range: -1 ~ 63
		min = 1
		#Range: 1 ~ 64
		max = 3
		#Range: -1 ~ 1000
		weight = 30

	[mobs.forsaken]
		#Range: -1 ~ 63
		min = 1
		#Range: 1 ~ 64
		max = 4
		#Range: -1 ~ 1000
		weight = 22

	[mobs.stoneguard]
		#Range: -1 ~ 63
		min = 1
		#Range: 1 ~ 64
		max = 2
		#Range: -1 ~ 1000
		weight = 34

	[mobs.desert_rabbit]
		#Range: -1 ~ 63
		min = 2
		#Range: 1 ~ 64
		max = 3
		#Range: -1 ~ 1000
		weight = 5

	[mobs.tarantula]
		#Range: -1 ~ 63
		min = 1
		#Range: 1 ~ 64
		max = 3
		#Range: -1 ~ 1000
		weight = 20

["mod integration"]
	champions = false
	theoneprobe = true

