
[items]

	[items.orb_of_temporary_flight]
		#Flight Time the Orb grants (in ticks) [default: 6000]
		#Range: 20 ~ 120000
		time = 6000

	[items.edelwood_bucket]
		#How many Water Blocks the Edelwood Bucket can store [default: 4]
		#Range: 1 ~ 10
		water_capacity = 4
		#How many Lava Blocks the Edelwood Bucket can store [default: 3]
		#Range: 1 ~ 10
		lava_capacity = 3
		#How much Milk the Edelwood Bucket can store [default: 4]
		#Range: 1 ~ 10
		milk_capacity = 4
		#How many Soups/Stews the Edelwood Bucket can store [default: 8]
		#Range: 1 ~ 10
		soup_capacity = 8

	[items.boom_arrow]
		#Should Boom Arrow explosions deal Block Damage [default: false]
		block_damage = false
		#Radius of Boom Arrow explosions [default: 3]
		#Range: 1 ~ 10
		explosion_radius = 3

	[items.mundabitur_dust]
		#Should right-clicking a Creeper with Mundabitur Dust charge the Creeper [default: true]
		charge_creeper = true

	[items.xpetrified_orb]
		#Experience Points the Orb grants on use [default: 91]
		#Range: 1 ~ 120000
		experience_points = 91

	[items.eternal_stella]
		#How many times the Eternal Stella can be used before breaking [default: 3]
		#Range: 1 ~ 100
		uses = 3

[block]

	[block.stella_arcanum]
		#Should Stella Arcanum explode when mined [default: true]
		explode = true
		#Should Stella Arcanum only explode when mined with a wrong tool (if explosions enabled) [default: false]
		only_explode_wrong_tool = false
		#Should Stella Arcanum explosions deal Block Damage (if explosions enabled) [default: true]
		block_damage = true
		#Radius of Stella Arcanum explosions (if explosions enabled) [default: 3]
		#Range: 1 ~ 10
		explosion_radius = 3

[rendering]

	[rendering.orb_of_temporary_flight]
		#Should the Orb of Temporary Flight Overlay be rendered? [default: true]
		render = true
		#X-Position of the Orb of Temporary Flight Overlay (if enabled) [default: 1]
		#Range: 0 ~ 500
		x_position = 1
		#Y-Position of the Orb of Temporary Flight Overlay (if enabled) [default: 1]
		#Range: 0 ~ 500
		y_position = 1

[enchantments]

	[enchantments.indestructible]
		#Damageable Items that shouldn't be able to contain the Indestructible Enchantment
		item_blacklist = ["tetra:modular_sword", "tetra:modular_single", "tetra:modular_double", "tetra:modular_bow", "tetra:modular_crossbow", "tetra:modular_shield"]
		#Enchantments that cannot be applied together with the Indestructible Enchantment
		enchantment_blacklist = ["minecraft:unbreaking", "minecraft:mending"]
		#Should the item be fully repaired after applying the Indestructible enchantment [default: true]
		fully_repair_item = true

