
#Common configuration settings
[common]
	#If true, prevents the trader from despawning if named
	preventDespawnIfNamed = true

	#Goblin Trader settings
	[common.goblin_trader]
		#The chance out of one hundred that the trader will spawn in the over world
		#Range: 1 ~ 100
		traderSpawnChance = 25
		#The amount of ticks before the trader will spawn again
		#Range: > 0
		traderSpawnDelay = 24000
		#The minimum level the trader can spawn
		#Range: 0 ~ 256
		traderMinSpawnLevel = 0
		#The maximum level the trader can spawn
		#Range: 0 ~ 256
		traderMaxSpawnLevel = 40
		#The amount of ticks before the trader will replenish it's trades. Set to -1 to disable restocking
		#Range: > -1
		restockDelay = 48000
		#If true, the goblin will try to hit back a player or mob that hit them first
		canAttackBack = true

	#Vein Goblin Trader settings
	[common.vein_goblin_trader]
		#The chance out of one hundred that the trader will spawn in the over world
		#Range: 1 ~ 100
		traderSpawnChance = 25
		#The amount of ticks before the trader will spawn again
		#Range: > 0
		traderSpawnDelay = 24000
		#The minimum level the trader can spawn
		#Range: 0 ~ 256
		traderMinSpawnLevel = 0
		#The maximum level the trader can spawn
		#Range: 0 ~ 256
		traderMaxSpawnLevel = 128
		#The amount of ticks before the trader will replenish it's trades. Set to -1 to disable restocking
		#Range: > -1
		restockDelay = 48000
		#If true, the goblin will try to hit back a player or mob that hit them first
		canAttackBack = true

