
#Settings for Inventory HUD
[inventoryhud]
	#Inventory HUD position (Y)
	#Range: -9999 ~ 9999
	yPos = -27
	#Inventory HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHalign = "MIDDLE"
	#Toggle on by default
	byDefault = false
	#Inventory HUD position (X)
	#Range: -9999 ~ 9999
	xPos = 25
	#Inventory HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invValign = "CENTER"

#Settings for ArmorStatus HUD
[armorhud]
	#Armor HUD position (X)
	#Range: -9999 ~ 9999
	xArmPos = 0
	#Armor HUD position (Y)
	#Range: -9999 ~ 9999
	yArmPos = 70
	#Armor HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	armHalign = "MIDDLE"
	#Armor HUD type (ARMOR, FULL, FULL and empty inventory slots)
	#Allowed Values: ARMOR, FULL, FULL_AND_INV
	armType = "ARMOR"
	#Is Armor Damage HUD enabled
	ArmorDamage = true
	#Hide if durability is above this (in percentage):
	#Range: 0 ~ 100
	armAbove = 100
	#Armor HUD durability view (PERCENTAGE, DAMAGE, DAMAGE LEFT)
	#Allowed Values: PERCENTAGE, DAMAGE, DAMAGE_LEFT
	armView = "DAMAGE_LEFT"
	#Armor HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	armValign = "BOTTOM"

#Settings for Potions HUD
[potionshud]
	#Is Potions HUD enabled
	Potions = true
	#Potion HUD position (Y)
	#Range: -9999 ~ 9999
	yPotionPos = 5
	#Potion HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	potValign = "TOP"
	#Potion HUD mini mode
	potMini = false
	#Potion HUD position (X)
	#Range: -9999 ~ 9999
	xPotionPos = 5
	#Potion HUD alpha
	#Range: 0 ~ 100
	potAlpha = 100
	#Potion HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	potHalign = "LEFT"
