
#Server and Client side changes.
[common]
	#If true, lava monsters do not require a source block to spawn.
	flowingLava = false
	#The distance a lava monster will begin attacking. (maximum of 35)
	monsterRange = 17.0
	#Number of fireballs shot with each attack.
	attackShots = 3
	#Allows you to add to the biomes the Lava Monster can spawn in, this does not change the existing biomes, only adds extra ones. Separate with commas. (By default, the Lava Monster will spawn in biomes tagged as nether or overworld.)
	extraBiomes = "good_nights_sleep:nightmare"
	#The number of ticks between each lava monster spawn attempt.
	spawnFrequency = 100
	#If true, lava monsters will not spawn above layer 16.
	depthHazard = true
	#The amount of armor lava monsters have.
	monsterArmor = 0.0
	#Ticks between each fireball shot in an attack.
	attackSpacing = 6
	#Ticks a monster must wait after attacking before it can start winding up again.
	attackCooldown = 80
	#Ticks it takes before a monster can start an attack.
	attackWindup = 60
	#The chance for a lava monster spawn attempt to be successful.
	spawnChance = 0.05
	#If true, lava monsters will be able to spawn in lava one block deep.
	shallowLava = false
