
[items]
	#If milkable mobs can be milked with empty glass bottles
	"Milking with Glass Bottles" = true
	#The use time for Milk Buckets, in ticks
	"Milk Bucket drink time" = 32

[worldgen]

	[worldgen.features]
		#Range: 0 ~ 128
		"Strawberry Bush generation chance in Plains" = 9
		#Range: 0 ~ 128
		"Vanilla Vine generation chance in Savannas" = 6
		#Range: 0 ~ 128
		"Aduzki Sprouts generation chance in Forests" = 7
		#Range: 0 ~ 128
		"Mint pond generation chance in Mountains" = 5
		"Banana Plant generation in Beaches" = true
		"Banana Plant generation in Jungles" = false

[entities]

	[entities.plantain_spider]
		"Plantain Spider spawning in Jungles" = true
		"Plantain Spider spawn from Banana Bundles" = true
		"Plantain Spiders give Slipping" = true

