
#Settings for Pandoras Creatures
[chat]
	#Turn the notification the player gets when joining and the mod detected an invalid .jar on and off.
	shouldShowInvalidJarMessage = true
	#Turn the notification the player gets when joining and a the mod wasnt able to check for a new version on and off.
	shouldShowUpdateCheckFailedMessage = true
	#Turn the notification the player gets when joining and a new update has been found on and off.
	shouldShowUpdateMessage = false

[creativeTabOptions]
	#Choose if the buttons that get rendered in the Pandoras Creatures Creative Tab should be disabled or enabled.
	shouldButtonsInCreativeTabBeEnabled = true
	#Offset the CurseForge Button on the Y axis
	buttonCurseForgeOffsetY = 0
	#Offset the Discord Button on the Y axis
	buttonDiscordOffsetY = 0
	#Offset the CurseForge Button on the X axis
	buttonCurseForgeOffsetX = 0
	#Offset the Discord Button on the X axis
	buttonDiscordOffsetX = 0
	#Offset the Twitch Button on the X axis
	buttonTwitchOffsetX = 0
	#Offset the Twitch Button on the Y axis
	buttonTwitchOffsetY = 0
	#The amount of seconds it takes for the buttons to fully appear. Set it to 0 in order to disable the fading
	#Range: 0 ~ 5
	buttonFadeInTime = 1
	#Offset the YouTube Button on the X axis
	buttonYouTubeOffsetX = 0
	#Offset the Patreon Button on the X axis
	buttonPatreonOffsetX = 0
	#Offset the YouTube Button on the Y axis
	buttonYouTubeOffsetY = 0
	#Offset the Patreon Button on the Y axis
	buttonPatreonOffsetY = 0
