
[General]
	#The number of item stacks held in a basic unit of storage.
	#1x1 drawers hold 8 units, 1x2 drawers hold 4 units, 2x2 drawers hold 2 units.
	#Half-depth drawers hold half those amounts.
	baseStackStorage = 4
	#Range: 1 ~ 50
	controllerRange = 12
	enableUI = true
	enableSidedInput = true
	enableSidedOutput = true
	enableItemConversion = true
	enableExtraCompactingRules = true
	debugTrace = false
	#List of rules in format "domain:item1, domain:item2, n".
	#Causes a compacting drawer convert 1 of item1 into n of item2.
	compactingRules = ["minecraft:clay, minecraft:clay_ball, 4", "minecraft:nether_wart_block, minecraft:nether_wart, 4"]

[StorageUpgrades]
	#Storage upgrades multiply storage capacity by the given amount.
	#When multiple storage upgrades are used together, their multipliers are added before being applied.
	level1Mult = 2
	level2Mult = 4
	level3Mult = 8
	level4Mult = 16
	level5Mult = 32

[Integration]
	wailaStackRemainder = true

