
#General options for defining sound effects
["Sound Options"]
	#Enable sound reverb and filtering
	"Enable Enhanced Sounds" = true
	#Enable sound occlusion calculations (sound muffling when positioned behind blocks)
	"Enable Sound Occlusion Calculations" = true
	#Enable conversion of stereo sounds to mono format for spacial play
	"Enable Stereo to Mono Conversion" = true
	#Enable enhanced sounds for weather effects
	"Enable Enhanced Weather Sounds" = true
	#Options to configure sounds on an individual basis
	"Individual Sound Config" = ["minecraft:entity.sheep.ambient cull", "minecraft:entity.chicken.ambient cull", "minecraft:entity.cow.ambient cull", "minecraft:entity.pig.ambient cull", "minecraft:entity.llama.ambient cull", "minecraft:entity.wither.death cull 25", "minecraft:entity.ender_dragon.death cull 25"]
	#Possible sounds to play when client reaches main game menu
	"Startup Sound List" = []
	#Ticks between culled sound events (0 to disable culling)
	#Range: > 0
	"Sound Culling Interval" = 20
	#Number of background threads to handle sound effect calculations (0 is default)
	#Range: 0 ~ 8
	"Background Workers" = 0

#Defines parameters for special effects
["Effect Options"]
	#Replace client side Randomizers with faster versions
	"Replace Randoms" = true
	#Block range of entity special effect handling
	#Range: 16 ~ 64
	"Block Range" = 24

#Defines how Sound Control logging will behave
["Logging Options"]
	#Enables/disables debug logging of the mod
	"Debug Logging" = false
	#Bitmask for toggling various debug traces
	#Range: > 0
	"Debug Flag Mask" = 0

